const routes = [
  {
    slug: "quin",
    name: "Alquin Suedad",
    imgPer: "/quin.jpg",
    about:
      "I love exploring new things, whether it’s diving into exciting technologies, learning a new skill, or embracing fresh experiences. Coding is a big part of my life—it challenges and inspires me to create something meaningful. When I'm not programming, you'll often find me playing the guitar, letting the music unwind my thoughts.",
    age: 18,
    birthday: "September 7, 2006",
    address: "Sungay East Tagaytay City",
    hobbies: [
      "Music Performing",
      "Wandering Alone",
      "Coding",
      "Spend time with my Dogs 'Molly' and 'Akie'",
    ],
    talents: ["Playing Instruments"],
    hero: "Hayabusa",
    heroImg: "/hayabusa-static.jpg",
    heroQuote: "“Make peace with your inner self.”",
    heroGif: "/hayabusa.gif",
    heroDesc:
      "He is a quiet, modest warrior who ensures peace in the Cadia Riverlands like a loyal, powerful, and sharp blade.",
  },
  {
    slug: "audrey",
    name: "Sinead Audrey Vallestero",
    imgPer: "/audrey.jpg",
    about:
      "A happy-go-lucky Millenial who has yet to decide on what to do with her life. Being an ambivert, I enjoy both being alone and being in groups. I like keeping memories and I value my loved ones and friends. My love language is giving gifts. I also treasure my professors and mentors for I believe they have made a significant impact on who I am today.",
    age: 29,
    birthday: "January 28, 1995",
    address:
      " Block 5 Lot 4 Phase 2C, Tagaytay Tropical Greens Subdivision, Barangay Patutong Malaki South, Tagaytay, Cavite",
    hobbies: [
      "listening to Music, watching anime, collecting anime figures",
      "Bonding with my favorite dog 'Yuki'.",
    ],
    talents: ["Singing", "Piano"],
    hero: "Zhuxin",
    heroImg: "/zhuxin.jpg",
    heroQuote:
      "“For nearly a thousand years, I have wandered in search of the purest wishes to fulfill, hoping one day to find my own.”",
    heroGif: "/zhuxin-static-gif.jpg",
    heroDesc:
      "An enigmatic young woman from the city of Zhu’an, nestled in the mountains of the Cadia Riverlands. She guides the Ember butterflies and walks between life and death using her Lantern of Spirits.",
  },
  {
    slug: "mariel",
    name: "Mariel Bernice Lepardo San Mateo",
    imgPer: "/mariel.jpg",
    about: `A soul of creativity and curiosity, I walk the path of growth and learning. My mind is sharp, my heart compassionate, and my spirit resilient. I thrive in the beauty of art, from drawing and painting to writing stories that inspire imagination. Guided by kindness and purpose, I seek to create meaningful connections and solve challenges with resourcefulness. With an open mind and unwavering determination, I strive to live a life filled with learning, peace, and moments that bring joy to those I cherish.`,
    age: 18,
    birthday: "October 12, 2006",
    address: "Anuling Cerca 1, Mendez Cavite",
    hobbies: [
      "Playing Chess",
      "Badminton, & Cards",
      "Watching Movies",
      "Cartoons and K-dramas",
      "Reading RomCom and Fantasy Books",
      "Listening to Music",
      "Playing and Bonding with cats",
      "Cooking Foods and Making Dessert",
    ],
    talents: ["Drawing", "Painting", "Creating Arts", "Writing Stories"],
    hero: "Kagura",
    heroImg: "/kagura-static.jpg",
    heroQuote: "“The umbrella is yang, the human is yin.”",
    heroGif: "/kagura.gif",
    heroDesc:
      "She is an Onmyouji Master, inheriting the ancestral treasure Seimei Umbrella from her legendary ancestor, Seimei.",
  },
  {
    slug: "ericka",
    name: "Ericka Mae Sagales",
    imgPer: "/ericka.jpeg",
    about: `A courageous individual who finds joy in watching Marvel movies and listening to BTS, whose music inspires me deeply. In my free time, I enjoy spending moments with my family, friends, and boyfriend, cherishing the peace and happiness they bring. I find fulfillment in exploring personal growth through articles and love learning about different topics. With a heart full of positivity and a love for what inspires me, I aim to live a life filled with meaningful connections and peaceful moments.`,
    age: 18,
    birthday: " April 10, 2006",
    address: "The Mandara Subd. Brgy Tartaria, Silang, Cavite.",
    hobbies: ["Watching movies", "K-POP"],
    talents: ["WALA"],
    hero: "Miya",
    heroImg: "/miya.jpg",
    heroQuote: "“The way of the hunter: moderate, respectful, and sincere.”",
    heroGif: "miya-gif.gif",
    heroDesc:
      "In order to protect her homeland, Miya, as the Priestess of the Moon, led the other Moon Elves in a defense against foreign enemies.",
  },
  {
    slug: "tanuyan",
    name: "Rosselene Tanuyan",
    imgPer: "/tanuyan.jpg",
    about: `A ray of sunshine, spreading joy and warmth wherever she goes. Her bright smile and infectious laughter brighten every day, inspiring others with her unwavering optimism and effortless charm.
`,
    age: 18,
    birthday: "December 30, 2005",
    address: "226, Purok 1, Banaba Lejos, Indang, Cavite",
    hobbies: ["Sleeping", "Eating", "Watching Animes", "Reading Comics"],
    talents: ["Singing"],
    hero: "Chang'e",
    heroImg: "/change-static.png",
    heroQuote: "“Though we are separate, we share the same view of stars.”",
    heroGif: "/change-gif.gif",
    heroDesc:
      "She is the youngest disciple of the Great Dragon and is infamous for her mischievous and playful nature.",
  },
  {
    slug: "bello",
    name: "Rio Mae Bello",
    imgPer: "/bello.png",
    about:
      "A passionate individual who finds joy in the world of art and creativity. From drawing and painting to exploring new mediums, I express myself through the beauty of colors and shapes. I cherish moments spent with family and loved ones, always striving to give back to them for their sacrifices. Driven by a deep sense of purpose, I work hard as a student to support both my education and my family. With a love for solitude and a heart full of determination, I seek to explore new artistic horizons and continuously grow in life.",
    age: 18,
    birthday: "April 1, 2006",
    address: " Brgy. Banay banay Amadeo Cavite",
    hobbies: ["Cooking", "Drawing", "Painting", "Video Games", "Watching"],
    talents: ["Drawing", "Painting"],
    hero: "Esmeralda",
    heroImg: "/esme-static.jpg",
    heroQuote: "“Ah! The stars are my beacon!”",
    heroGif: "/esme-gif.gif",
    heroDesc:
      "She is the greatest astrologers on the Land of Dawn. Through the treasure star-moon box, she learned the fact that the tyrant Khufra was about to wake up.",
  },
  {
    slug: "yongis",
    name: "Abegael Yongis",
    imgPer: "/yongis.jpeg",
    about:
      "An introverted girl who loves quiet moments and spending time with cats and dogs. Their company makes her happy and brings her peace. She’s a big fan of EXO and bands (WDW, 1D, The Vamps) and loves to go to any concerts. When she’s not immersed in music or cuddling with her furry friends, she enjoys drawing, photography, and getting lost in K-dramas and Wattpad. A soft-hearted soul where she finds happiness in the little things and values peaceful moments.",
    age: 19,
    birthday: "September 13, 2005",
    address:
      " Legarda Street, Castaños Cerca, General Emilio Aguinaldo, Cavite.",
    hobbies: [
      "Drawing",
      "Photography",
      "Listening to Music",
      "Watching K-Drama/Movies",
      "Reading Wattpad and Novels",
      "Sleeping",
      "Eating",
    ],
    talents: ["Drawing", "Singing"],
    hero: "Guinevere",
    heroImg: "/guine-static.jpg",
    heroQuote: "“I'm born with talent.”",
    heroGif: "/guine-gif.gif",
    heroDesc:
      " She is the youngest daughter of the noble House Baroque and has been studying magic since childhood.",
  },
  {
    slug: "mirakel",
    name: "Ehd Miracle Perez Paiton",
    imgPer: "/mirakel.jpeg",
    about:
      "I am a skilled and talented individual, especially when it comes to sports and math. I am very sporty, excelling in the games I play and always giving my best on the field. At the same time, I have a strong ability to solve math problems, which shows my focus and sharp thinking. Whether it’s physical activities or academics, I always strive to perform at my best.",
    age: 19,
    birthday: "September 16, 2005",
    address: "303, Lopes Jaena St. Pob.2 GEA-BAILEN",
    hobbies: [
      "Playing Volleyball",
      "Playing Chess",
      "Stroll Around",
      " Going to gym every weekend",
    ],
    talents: ["Good at everything i play"],
    hero: "Floryn",
    heroImg: "/floryn-static.jpg",
    heroQuote: `"Let's make the whole world green and lively."
`,
    heroGif: "/floryn.gif",
    heroDesc:
      "A kind-hearted girl who is determined to spread greenery throughout the world.",
  },
  {
    slug: "moises",
    name: "Moises Patrick Andales",
    imgPer: "/moises.jpg",
    about:
      " I am the person who likes to play online games, and I love watching horror movies, and most of all, I also like to cook.",
    age: 19,
    birthday: "May 6, 2005",
    address: "Purok 189, Sungay west, Tagaytay City",
    hobbies: ["Playing Video Games"],
    talents: ["Drawing"],
    hero: "Balmond",
    heroImg: "/balmond-static.jpg",
    heroQuote: "“AJSLKHFLSHDFJSDFJKVKJCHF”",
    heroGif: "balmond-gif.gif",
    heroDesc: "Leader of the orc legion.",
  },
  {
    slug: "abion",
    name: "Cedric Nase Abion",
    imgPer: "/abion.jpg",
    about:
      "A man who loves to skate and to learn many things, also loves to style",
    age: 21,
    birthday: "June 14,2003",
    address: " Imperial Homes Tartaria Silang Cavite",
    hobbies: ["Skateboarding"],
    talents: ["None"],
    hero: "Helcurt",
    heroImg: "/helcurt-static.jpg",
    heroQuote: '"Uwing uwi na ak"',
    heroGif: "/helcurt-gif.gif",
    heroDesc:
      "The nightmare of the Abyss who's Willing to betray anyone in order to survive.",
  },
];

export default routes;
